### PR TITLE
[FIX] memcached session lock when session expired

### LINKED ISSUE #145: SESSION_TYPE memcache reload delay
When using the `memcache` option for the SESSION_TYPE I get delay of abt 30 sec when session has expired and login screen needs to be displayed again.
There is no such delay when using the `file` option.

Any idea what might cause this?

### PR DESCRIPTION
**Pull request by georgehristov**
Fixes #145

### CODE REVIEW

File: include/session.php [hunk 1]
```diff
@@ -211,6 +211,7 @@ public static function destroy_client($name,$i) {
             case 'memcache':
                 for($k=0;;$k++)
                     if(!self::$memcached->delete(MEMCACHE_SESSION_TOKEN.$name.'_'.$i.'/'.$k)) break;
+                self::$memcached->unlock(MEMCACHE_SESSION_TOKEN.$name);
```
Comment (bukowskiadam) [inline include/session.php]: I think that there should be CID included in the key.
```
self::$memcached->unlock(MEMCACHE_SESSION_TOKEN.$name.'_'.$i);
```
because of line 112
```
if(!READ_ONLY_SESSION && !self::$memcached->lock(MEMCACHE_SESSION_TOKEN.$name.'_'.CID,self::$memcached_lock_time))
```

Comment (georgehristov) [inline include/session.php]: You might be correct but I need to look into it a bit deeper.
I was looking at line 80
```
if(!READ_ONLY_SESSION && !self::$memcached->lock(MEMCACHE_SESSION_TOKEN.$name,self::$memcached_lock_time))
```

Comment (bukowskiadam) [inline include/session.php]: Sure, because session is divided into two parts. One global - one for every session_id (without CID), and separate for each opened tab/window (with CID).

**Comment by georgehristov** [comment]
Corrected now for the client session
